apiVersion: v1
kind: Template
labels:
  template: celery-flower-deploymentconfig
  thoth: 1.0.0
metadata:
  name: celery-flower-deploymentconfig
  annotations:
    description: Selinon Celery Flower
    openshift.io/display-name: 'Selinon: Celery Flower'
    version: 1.0.0
    tags: poc,selinon,celery-flower
    template.openshift.io/documentation-url: https://github.com/selinon/
    template.openshift.io/long-description: Selinon Celery Flower deployment configuration template.
    template.openshift.io/provider-display-name: Fridolin Pokorny

objects:

- kind: Route
  apiVersion: v1
  metadata:
    name: celery-flower
    labels:
      app: selinon
      component: celery-flower
  spec:
    to:
      kind: Service
      name: celery-flower

- kind: Service
  apiVersion: v1
  metadata:
    labels:
      service: celery-flower
      app: selinon
      component: celery-flower
    name: celery-flower
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 5555
    selector:
      service: celery-flower


- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: celery-flower
      app: selinon
      component: celery-flower
    name: celery-flower
  spec:
    replicas: 1
    selector:
      service: celery-flower
    template:
      metadata:
        labels:
          service: celery-flower
      spec:
        containers:
        - env:
          - name: CELERY_BROKER_URL
            value: 'amqp://guest:guest@rabbitmq:5672//'
          name: celery-flower
          ports:
            - containerPort: 5555
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "500m"
              #          readinessProbe:
              #            httpGet:
              #              path: '/'
              #              port: 5555
              #              scheme: HTTP
              #            initialDelaySeconds: 5
              #            periodSeconds: 10
              #            timeoutSeconds: 10
              #          livenessProbe:
              #            # TODO: create liveness
              #            httpGet:
              #              path: '/'
              #              port: 5555
              #              scheme: HTTP
              #            initialDelaySeconds: 5
              #            periodSeconds: 60
              #            timeoutSeconds: 10
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - celery-flower
        from:
          kind: ImageStreamTag
          name: 'celery-flower:latest'
