apiVersion: v1
kind: Template
labels:
  template: selinon-configmap
  selinon: 1.0.0
metadata:
  name: selinon-configmap
  annotations:
    description: Application deployment configuration.
    openshift.io/display-name: Selinon Configmap
    version: 1.0.0
    tags: poc,selinon,configmap
    template.openshift.io/documentation-url: https://github.com/selinon
    template.openshift.io/long-description: Configuration used in Selinon deployment to OpenShift.
    template.openshift.io/provider-display-name: Fridolin Pokorny

objects:

- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: selinon
    labels:
      app: selinon
  data:
    broker-url: ${BROKER_URL}
    postgres-user: ${POSTGRESQL_USER}
    postgres-database: ${POSTGRESQL_DATABASE}
    postgres-port: ${POSTGRESQL_PORT}
    postgres-ssl: disable
    pgbouncer-host: ${PGBOUNCER_HOST}
    pgbouncer-port: ${PGBOUNCER_PORT}
    mongo-user: ${MONGODB_USER}
    mongo-database: ${MONGODB_DATABASE}
    redis-port: ${REDIS_PORT}
    redis-host: ${REDIS_HOST}
    redis-database: ${REDIS_DATABASE}

parameters:
  - description: URL to message broker to be used. Defaults to RabbitMQ. Adjust for others - e.g. SQS.
    displayName: Message broker URL.
    required: true
    name: BROKER_URL

  - description: PostgreSQL user.
    displayName: PostgreSQL user.
    required: true
    name: POSTGRESQL_USER

  - description: PosgtreSQL database name.
    displayName: PostgreSQL database name.
    required: true
    name: POSTGRESQL_DATABASE

  - description: PostgreSQL database port.
    displayName: PostgreSQL database port.
    required: true
    name: POSTGRESQL_PORT

  - description: pgbouncer host.
    displayName: pgbouncer host.
    required: true
    name: PGBOUNCER_HOST

  - description: pgbouncer port.
    displayName: pgbouncer port.
    required: true
    name: PGBOUNCER_PORT

  - description: MongoDB user.
    displayName: MongoDB user.
    required: true
    name: MONGODB_USER

  - description: MongoDB database name.
    displayName: MongoDB database name.
    required: true
    name: MONGODB_DATABASE

  - description: Redis port.
    displayName: Redis port.
    required: true
    name: REDIS_PORT

  - description: Redis host.
    displayName: Redis host.
    required: true
    name: REDIS_HOST

  - description: Redis database name.
    displayName: Redis database name.
    required: true
    name: REDIS_DATABASE
