apiVersion: v1
kind: Template
labels:
  template: pgbouncer-deploymentconfig
  thoth: 1.0.0
metadata:
  name: pgbouncer-deploymentconfig
  annotations:
    description: Selinon pgbouncer
    openshift.io/display-name: 'Selinon: pgbouncer'
    version: 1.0.0
    tags: poc,selinon,postgres,pgbouncer
    template.openshift.io/documentation-url: https://github.com/selinon/
    template.openshift.io/long-description: Selinon pgbouncer deployment configuration template.
    template.openshift.io/provider-display-name: Fridolin Pokorny

objects:
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      service: pgbouncer
      app: selinon-storages
      component: pgbouncer
    name: pgbouncer
  spec:
    ports:
    - port: 6432
      protocol: TCP
      targetPort: 6432
    selector:
      service: pgbouncer

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: pgbouncer
      app: selinon-storages
      component: pgbouncer
    name: pgbouncer
  spec:
    replicas: 1
    selector:
      service: pgbouncer
    template:
      metadata:
        labels:
          service: pgbouncer
      spec:
        containers:
        - env:
          - name: POSTGRES_PORT
            value: tcp://postgres:5432
          - name: POSTGRES_ENV_POSTGRES_USER
            value: user
          - name: POSTGRES_ENV_POSTGRES_DB
            value: selinon
          - name: POSTGRES_ENV_POSTGRES_PASSWORD
            value: postgres
          name: pgbouncer
          ports:
            - containerPort: 6432
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "750m"
              #          readinessProbe:
              #            httpGet:
              #              path: '/'
              #              port: 5555
              #              scheme: HTTP
              #            initialDelaySeconds: 5
              #            periodSeconds: 10
              #            timeoutSeconds: 10
              #          livenessProbe:
              #            # TODO: create liveness
              #            httpGet:
              #              path: '/'
              #              port: 5555
              #              scheme: HTTP
              #            initialDelaySeconds: 5
              #            periodSeconds: 60
              #            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /etc/pgbouncer
              name: pgbouncer-volume
            - mountPath: /var/log/pgbouncer
              name: pgbouncer-log-volume
        volumes:
        - name: pgbouncer-volume
          emptyDir: {}
        - name: pgbouncer-log-volume
          emptyDir: {}

    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - pgbouncer
        from:
          kind: ImageStreamTag
          name: 'pgbouncer:1.6.1'
