apiVersion: v1
kind: Template
labels:
  template: pgweb-deploymentconfig
  thoth: 1.0.0
metadata:
  name: pgweb-deploymentconfig
  annotations:
    description: Selinon pgweb
    openshift.io/display-name: 'Selinon: pgweb'
    version: 1.0.0
    tags: poc,selinon,postgres,pgweb
    template.openshift.io/documentation-url: https://github.com/selinon/
    template.openshift.io/long-description: Selinon pgweb deployment configuration template.
    template.openshift.io/provider-display-name: Fridolin Pokorny

objects:

- kind: Route
  apiVersion: v1
  metadata:
    name: pgweb
    labels:
      app: selinon-storages
      component: pgweb
  spec:
    to:
      kind: Service
      name: pgweb

- kind: Service
  apiVersion: v1
  metadata:
    labels:
      service: pgweb
      app: selinon-storages
      component: pgweb
    name: pgweb
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      service: pgweb

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: pgweb
      app: selinon-storages
      component: pgweb
    name: pgweb
  spec:
    replicas: 1
    selector:
      service: pgweb
    template:
      metadata:
        labels:
          service: pgweb
      spec:
        containers:
        - env:
          - name: DB_HOST
            value: postgres
          - name: DB_PORT
            value: '5432'
          - name: DB_DATABASE
            value: selinon
          - name: DB_USER
            value: user
          - name: DB_PASSWORD
            value: postgres
          - name: DB_SSL
            value: disable
          - name: URL
            value: "postgres://user:postgres@postgres:5432/database?sslmode=disable"
          name: pgweb
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: '/'
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: '/'
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 60
            timeoutSeconds: 10
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - pgweb
        from:
          kind: ImageStreamTag
          name: 'pgweb:latest'
